Platform 360 - Environmental Health Form Config
hopetambala/puente-reactnative-collect pull request #410
Opened 2021-08-05 01:43 UTC by jamesgiegerich94

### Description of proposed changes
_What does this pull request accomplish? Why should it be integrated?_

### Checklist
_Put an `x` in the boxes that apply._
- [ ] My lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my changes work (if applicable)
- [ ] I have added or updated necessary documentation (if appropriate)

### Additional comments
_Is there anything else you want us to know?_

2021-08-17 05:59 UTC, hopetambala commented
@jamccomb92 this looks good to me! approve if it looks good to you

2021-08-17 22:44 UTC, jamccomb92 commented on domains/DataCollection/Forms/SupplementaryForm/configs/envhealth.config.js
> +        value: 'N'
Let's change this value to None

2021-08-17 22:45 UTC, jamccomb92 commented on domains/DataCollection/Forms/SupplementaryForm/configs/envhealth.config.js
> +        value: 'Clinic/Medical_Center'
I'd prefer that the key does not include '/'

2021-08-17 22:46 UTC, jamccomb92 commented on domains/DataCollection/Forms/SupplementaryForm/configs/envhealth.config.js
> +        value: 'Y'
Don't think we should be changing the value of question. All others collected will not match those previously collected. Leave as Yes

2021-08-17 22:47 UTC, jamccomb92 commented on domains/DataCollection/Forms/SupplementaryForm/configs/envhealth.config.js
> +        value: 'N'
Don't think we should be changing the value of question. All others collected will not match those previously collected. Leave as No

2021-08-17 22:48 UTC, jamccomb92 commented on domains/DataCollection/Forms/SupplementaryForm/configs/envhealth.config.js
> +    formikKey: 'floorCondition',
why are we changing the formikKey? all other values collected will be in separate field

2021-08-17 22:49 UTC, jamccomb92 commented on domains/DataCollection/Forms/SupplementaryForm/configs/envhealth.config.js
> +        value: '6-12'
prefer consistent value 6_12

2021-08-17 22:49 UTC, jamccomb92 commented on domains/DataCollection/Forms/SupplementaryForm/configs/envhealth.config.js
> +        value: '13-18'
13_18

2021-08-17 22:51 UTC, jamccomb92 commented on domains/DataCollection/Forms/SupplementaryForm/configs/envhealth.config.js
> +        label: 'environmentalHealth.clinicAccess.None',
change to None

2021-08-17 22:55 UTC, jamccomb92 requested changes
This all looks great! I would make the changes I commented on. Also in terms of all keys, I think we should stick to a consistent naming convention for values whether that be camelCase or underscores. I'd also avoid adding any special characters like '/' or '-'. It's a bit nit picky but I'd prefer consistent naming conventions where we can control, so I would ensure that all values match, maybe that wasnt the case before and if it isnt only make the requested changes. If all others are consistent camelCase or under_score lets stick to it throughout the form.

2021-08-18 03:38 UTC, jamccomb92 approved these changes
Everything looks great! thanks @jamesgiegerich94

2021-08-18 04:22 UTC, hopetambala approved these changes

2021-08-18 04:22 UTC, merged